# Enable or disable update message
update-checker: true

# Opens random chest
random-chests: false

# If you have your old own cooldowns and you don't trust enough about new system,
# just switch this option to true.
old-cooldown-parse: false

# Currently, this option works only with HolographicDisplays - it sends hologram with information about the cooldown
holograms-on-chests: false

chest-add-sound: ENTITY_EXPERIENCE_ORB_PICKUP

# In database, this plugin saves information about cooldowns to chests. If it is disabled, all cooldowns after reload plugin
# or server shutdown, will disappear.
database:
  use: false
  type: "YAML"
  #in seconds
  auto-save-time: 300
  host: "localhost"
  user: "user"
  password: "password"
  database: "database"
  port: 3306

wand-item:
  displayName: '&6Chest Wand'
  permission-to-use: true
