name: ${project.artifactId}
version: ${project.version}
main: me.mrsandking.github.randomlootchest.RandomLootChestMain
author: MrABCDevelopment
api-version: 1.13

commands:
  chests:
    permission: chests.use
    permission-message: You cannot use this command.
    description: The main command of RandomLootChest plugin.