name: ${project.name}
version: ${project.version}
main: me.dreamdevs.github.randomlootchest.RandomLootChestMain
author: MrABCDevelopment
api-version: 1.13

softdepend: [MMOItems, PlaceholderAPI]

commands:
  randomlootchest:
    aliases: [rlc, randomchest, chests]
    permission: randomlootchest.admin
    permission-message: You cannot use this command.
    description: The main command of RandomLootChest plugin.