#Bez względu na ustawioną skrzynię na danej lokacji, otworzy się losowa skrzynia.
random-chests: false

#Cząsteczki nad skrzyniami.
particles:
  active: true
  amount: 1
  type: "HEART"

database:
  use: false
  type: "YAML"
  #in seconds
  auto-save-time: 300
  host: "localhost"
  user: "user"
  password: "password"
  database: "database"
  port: 3306

wand-item:
  displayName: '&6Chest Wand'
  permission-to-use: true

#Jest to mini-dodatek możesz po prostu usunąć wszystko z listy aby nic on nie dodawał na starcie.
#Jednak jeśli cię on zainteresował to działa on w następujący sposób,
#na starcie gracz otrzymuje wszystkie przedmioty z listy jednak SET nie wypada z niego!
start-items:
  - IRON_HELMET
  - IRON_CHESTPLATE
  - IRON_LEGGINGS
  - IRON_BOOTS
  - IRON_SWORD:1:&b&lMiecz:&7Je;&8je;&9je
