name: RandomLootChest
version: 1.2.0
main: me.mrsandking.github.randomlootchest.RandomLootChestMain
author: MrABCDevelopment

commands:
  chests:
    permission: chests.use
    permission-message: You cannot use this command.
    description: The main command of RandomLootChest plugin.