name: RandomLootChest
version: 1.4.0
main: me.mrsandking.github.randomlootchest.RandomLootChestMain
author: MrABCDevelopment
api-version: 1.13
softdepend:
  - Vault
  - HolographicDisplays

commands:
  randomlootchest:
    aliases: [rlc, randomchest, chests]
    permission: chests.use
    permission-message: You cannot use this command.
    description: The main command of RandomLootChest plugin.