# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path
name: JavaDocs Maven Deploy

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 16
      uses: actions/setup-java@v3
      with:
        java-version: '16'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

 #   - name: Build Javadocs
 #     run: |
 3       echo "Building javadocs with gradle"
 #       mvn javadoc:jar
 #       echo "Moving to javadocs directory:"
 #       mkdir build/ && mkdir build/docs/ && mkdir build/docs/javadoc/
 #       cd build/docs/javadoc/
 #       echo "Creating .nojekyll to have Github pages deploy html as is:"
 #       touch .nojekyll

  #  - name: Deploy
  #    uses: MrABCDevelopment/github-pages-deploy-action@4.2.0
  #    with:
  #      branch: gh-pages # The branch the action should deploy to.
 #       folder: build/docs/javadoc/ # The folder the action should deploy.
